# personnaliser le site à votre marque en remplaçant
# nom_intuition par le nom de votre intuition
# mon_equipe par le nom de votre équipe
# 
intuition:  LavoLinge
nom_equipe: adibouteam
code_equipe: 2a

theme: jekyll-theme-dinky
